import type { NextPage } from 'next';
import Head from 'next/head';
import {ToDo} from "@src/components/root/"
import React, { useState } from "react"
import { EventType } from '@src/types/root';

const Home: NextPage = () => {
  const [lists, setLists] = useState <string[]>([])
    const [myInput, setMyInput] = useState <string> ("")
   
    const toDoHandler = (e:EventType):void => {
        e.preventDefault();
        setMyInput (e.target.value)
    }
    const addDataHandler = (e:EventType):void =>{ 
        e.preventDefault(); 
        myInput && setLists ([...lists, myInput])
    }
    const clearHandler = (e:EventType): void => {
      e.preventDefault(); 
      setLists ([])
    }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="section-padding-primary">
        <div className="container">
          <div className="bg-primaryGradient rounded-lg p-[20px] lg:p-[40px] text-center">
            <h1 className="text-white text-[1.875rem] lg:text-[3rem] font-medium lg:font-bold">
              Welcome to BrightonSEO
            </h1>
            
          </div>
          <div className = {` `}>
            <ToDo
              toDoTitle='My Diary'
              inputFieldProps={
                {
                  type: "text",
                  placeholder: "Set your schedule",
                  value: myInput,
                  name: myInput,
                  onChange: toDoHandler,
                  buttonProps: {
                    label: "Add New Schedule",
                    onCLick: addDataHandler
                  }
                }
              }
              lists = {
                {
                  lists
                }
              }
              clearHandler = {clearHandler}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
